### ISSUE TITLE
WikiMed JA and Wikimed ZH can not be published anymore

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android-custom#103] opened 2023-07-18 12:31 UTC

**Comment by kelson42** [comment] 2023-07-18 12:32
@gouri-panda I had a look, but no clue because the bot has the same permissions for these 2 apps as for the others.

**Comment by gouri-panda** [comment] 2023-10-21 11:08
@kelson42 I updated both of these apps in September. So, I'm closing this ticket.

**Comment by kelson42** [comment] 2023-10-21 11:11
Wikimedja is not updated, see last update on playstore https://play.google.com/store/apps/details?id=org.kiwix.kiwixcustomwikimedja

**Comment by gouri-panda** [comment] 2023-10-21 11:26
Weird! In the console, it says it's in the production.

**Comment by gouri-panda** [comment] 2023-10-21 11:31
@kelson42 I see now where the problem is even though it says it's in production.
<img width="1440" alt="Screenshot 2023-10-21 at 16 58 54" src="https://github.com/kiwix/kiwix-android-custom/assets/43576162/7c0e5a00-ec5f-4ae5-a81f-f6e3667a1652">

**Comment by kelson42** [comment] 2023-11-04 14:59
Explanation is clearly given in the admin panel IMO:
![image](https://github.com/kiwix/kiwix-android-custom/assets/1029718/0b250b2d-42cf-4503-90e0-3beabd933308)

**Comment by kelson42** [comment] 2023-12-29 16:28
@gouri-panda Any reason why this ticket is still open?

**Comment by gouri-panda** [comment] 2023-12-29 16:36
@kelson42 We can close this now. Wikimed  JA is live and Wikimed ZH is under review. The issue is irrelevant now.

**Closed by gouri-panda** 2023-12-29 16:36 UTC
Labels: bug, prio1
