### ISSUE TITLE
Share and update custom APK without having to go through Google play

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android-custom#61] opened 2020-04-20 11:19 UTC
It would be nice to be able to generate a custom app (like we currently do [here](https://github.com/kiwix/kiwix-android-custom/blob/master/README.md#Releasing)) but without going through the Playstore.

At the end of the process we would have a working apk that can be shared directly with users.

**Comment by kelson42** [comment] 2020-04-20 12:29
@macgills Maybe this is just a documentation thing?

**Comment by macgills** [comment] 2020-04-20 14:48
This is not feasible currently I would say.

We currently upload the zimfile to the play listing as an expansion file, when a user tries to download the app google gives them the apk and zim file in the 1 download.

There is a fallback mechanism where we download the file from our own servers on launch of the app if we can't find the google file.

I think what is desired here is the offline distribution version which is not yet supported from kiwixlib.

If we were to also publish our apks to download.kiwix then the users would have to launch the app to begin the zim download

**Comment by gouri-panda** [comment] 2023-12-29 18:36
@kelson42 I think this is feasible now with the play asset. Unlike the expansion file, we can download it in real-time.

**Comment by kelson42** [comment] 2023-12-30 10:07
@gouri-panda OK, could you please elaborate about how it would work and explicit the differences at both technical and end-user level between thatbkind of version and the current playstore version?

**Comment by gouri-panda** [comment] 2023-12-30 11:06
@kelson42 Sure! Here are the details on technical side.

If we want to update or change assets in our app without releasing a new version on the Google Play Store, we can leverage the on-demand delivery feature provided by Play Asset Delivery. This way, we can upload new asset packs to the Play Console without requiring a full app update.

Here are the general steps to achieve this:

1.  Create Asset Packs:
Organize our assets into asset packs. These packs should contain the resources you want to update or add.
In the Play Console, go to the "Play Asset Delivery" section, and under "Asset Packs," you can upload and manage your asset packs.

2. Update Asset Packs:
Whenever we need to update or add new assets, create a new version of the asset pack in the Play Console. This will generate a new pack with an updated version code.
We can upload our new assets as a new asset pack, and users will be able to download them on demand.

3. Use the AssetPackManager API:
In our app code we'll use the AssetPackManager API to request and download the updated asset packs when needed. We can specify the version of the asset pack you want to download.

4. Handle Asset Pack Updates:
Implement logic in our app to detect when new assets are available and trigger the download using the AssetPackManager. This ensures that users get the latest assets when they use the corresponding features in your app.


In the end user will be notified just to download new asset packs or not.

Key challenges:
The `on-demand` asset pack download limit is only 512MB. But if we can add each chunk to a UUID and only update the changed part with a new chunk. If this is technically possible then we can achieve this. It'll allow also users to download the updated parts without worrying about the large full-size apps.

**Comment by kelson42** [comment] 2023-12-30 11:59
> At the end of the process we would have a working apk that can be shared directly with users.

@gouri-panda IMHO you don't have undertodd the ticket.

**Comment by kelson42** [comment] 2023-12-30 12:00
> > At the end of the process we would have a working apk that can be shared directly with users.
> 
> @gouri-panda IMHO you don't have undertodd the ticket. This request a apk or aab file directly installable.

**Comment by gouri-panda** [comment] 2023-12-30 12:03
@kelson42 I see! I think this is much related to #60. I misunderstood the ticket.

**Comment by kelson42** [comment] 2023-12-30 12:07
> @kelson42 I see! I think this is much related to #60. I misunderstood the ticket.

This ticket is not related to #60 because everything should be in the apk or bundle.

**Comment by kelson42** [comment] 2024-02-03 15:13
@gouri-panda @macgills What stops us to make big APK or AAB file to be distributed and installed directly?

**Comment by gouri-panda** [comment] 2024-02-06 16:15
@kelson42 Sure! Let me research on that.

**Comment by kelson42** [comment] 2024-07-13 09:39
Duplicate of #66

**Closed by kelson42** 2024-07-13 09:39 UTC
Labels: enhancement, question
